// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE

import * as Curry from "../node_modules/bs-platform/lib/es6/curry.js";
import * as Tea_app from "../node_modules/bucklescript-tea/src-ocaml/tea_app.js";
import * as Tea_cmd from "../node_modules/bucklescript-tea/src-ocaml/tea_cmd.js";
import * as Tea_sub from "../node_modules/bucklescript-tea/src-ocaml/tea_sub.js";
import * as Tea_html from "../node_modules/bucklescript-tea/src-ocaml/tea_html.js";
import * as Tea_mouse from "../node_modules/bucklescript-tea/src-ocaml/tea_mouse.js";

function next(param) {
  switch (param) {
    case 0 : 
        return /* Green */1;
    case 1 : 
        return /* Blue */2;
    case 2 : 
        return /* White */3;
    case 3 : 
        return /* Yellow */4;
    case 4 : 
        return /* Red */0;
    
  }
}

function to_rgb(param) {
  switch (param) {
    case 0 : 
        return "#ff0000";
    case 1 : 
        return "#00ff00";
    case 2 : 
        return "#0000ff";
    case 3 : 
        return "#ffffff";
    case 4 : 
        return "#ffff00";
    
  }
}

var Color = /* module */[
  /* next */next,
  /* to_rgb */to_rgb
];

function init(param) {
  return /* tuple */[
          /* record */[
            /* coords : tuple */[
              0,
              0
            ],
            /* color : Red */0
          ],
          Tea_cmd.none
        ];
}

function update(model, msg) {
  var new_model = msg ? /* record */[
      /* coords : tuple */[
        msg[0],
        msg[1]
      ],
      /* color */model[/* color */1]
    ] : /* record */[
      /* coords */model[/* coords */0],
      /* color */next(model[/* color */1])
    ];
  return /* tuple */[
          new_model,
          Tea_cmd.none
        ];
}

var Model = /* module */[
  /* init */init,
  /* update */update
];

function subscriptions(model) {
  return Tea_sub.batch(/* :: */[
              Tea_mouse.moves(undefined, (function (mouse_pos) {
                      return /* MouseMove */[
                              mouse_pos[/* x */0],
                              mouse_pos[/* y */1]
                            ];
                    })),
              /* :: */[
                Tea_mouse.ups(undefined, (function (param) {
                        return /* Click */0;
                      })),
                /* [] */0
              ]
            ]);
}

var partial_arg_000 = Tea_html.id("playField");

var partial_arg_001 = /* :: */[
  Tea_html.style("width", "100%"),
  /* :: */[
    Tea_html.style("height", "100%"),
    /* :: */[
      Tea_html.style("background-color", "black"),
      /* :: */[
        Tea_html.style("margin", "0"),
        /* [] */0
      ]
    ]
  ]
];

var partial_arg = /* :: */[
  partial_arg_000,
  partial_arg_001
];

function play_field(param) {
  return Tea_html.div(undefined, undefined, partial_arg, param);
}

function square(model) {
  var match = model[/* coords */0];
  return Tea_html.div(undefined, undefined, /* :: */[
              Tea_html.id("playerSquare"),
              /* :: */[
                Tea_html.style("background-color", to_rgb(model[/* color */1])),
                /* :: */[
                  Tea_html.style("height", "50px"),
                  /* :: */[
                    Tea_html.style("width", "50px"),
                    /* :: */[
                      Tea_html.style("position", "absolute"),
                      /* :: */[
                        Tea_html.style("top", String(match[1] - 25 | 0)),
                        /* :: */[
                          Tea_html.style("left", String(match[0] - 25 | 0)),
                          /* [] */0
                        ]
                      ]
                    ]
                  ]
                ]
              ]
            ], /* [] */0);
}

function render(model) {
  return Curry._1(play_field, /* :: */[
              square(model),
              /* [] */0
            ]);
}

var View = /* module */[
  /* play_field */play_field,
  /* square */square,
  /* render */render
];

var partial_arg$1 = /* record */[
  /* init */init,
  /* update */update,
  /* view */render,
  /* subscriptions */subscriptions
];

function main(param, param$1) {
  return Tea_app.standardProgram(partial_arg$1, param, param$1);
}

export {
  Color ,
  Model ,
  subscriptions ,
  View ,
  main ,
  
}
/* partial_arg Not a pure module */
